server:
  port: 5000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

middleware:
  backend-service:
    url: http://localhost:8081/api
openai:
  api:
    key: 3718b706-6942-4737-98a6-f648931a1eeb